In [1]:
# Data Structure
# name: str
# temp: [["A", 37], ["B", 36]]
# assembly: str
# trna: str (the one tRNA scan produces most trna)
# trna_count: int (the number of tRNA found in the genome)

# Discard CSV
# name: str
# assembly: str
# reason_for_discard: str
# dataset: str

In [2]:
import pandas as pd
import re
from numpy import mean, nan
import subprocess, requests, tarfile, os
from zipfile import ZipFile
from pybarrnap import Barrnap
from pybarrnap.utils import load_example_fasta_file

# Read in the data
df = pd.read_csv("eukaryotes_ncbi_temperatures.csv")

columns = ["#Organism Name", "Organism Groups", "Assembly", "Temperature (°C)"]
df = df[columns]
df = df.dropna(subset="Temperature (°C)")
df = df.loc[df['Organism Groups'].str.contains("Fung")]
df.drop_duplicates(subset="Assembly")

# Extract species root names
df['species_root_name'] = df['#Organism Name'].apply(lambda item: " ".join(item.split(" ")[:2]))
df['species_root_name'] = df['species_root_name'].apply(lambda item: re.sub(r"[\[\];'\",\(\).;\-]", "", item))

# Identify duplicates based on species root names
df['duplicate'] = df.duplicated(subset="species_root_name", keep=False)

# Remove entries with " cf. " in the organism name
df = df.loc[~df['#Organism Name'].str.contains(" cf. ")]
df = df.reset_index(drop=True)
df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
0,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
1,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
2,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
3,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
4,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False

In [3]:
####### CLEAN CSV B #######
from Bio import Entrez
import time

Entrez.email = "michalewiczn@queens.edu"

df_b = pd.read_csv("temperature_data.tsv", sep="\t")
df_b = df_b.loc[df_b["lineage_text"].str.contains("Fungi")].dropna(subset="temperature")
df_b = df_b.loc[(~df_b["temperature"].gt(100)) | (~df_b["temperature"].eq(25))].reset_index(drop=True)

def get_assembly(df: pd.DataFrame, dataset: str) -> pd.DataFrame:
    df2 = df.copy()
    columns = ["name", "taxid", "assembly", "reference", "temp"]
    rows = []
    
    # for row in range(len(df2)):
    for row in range(10):
        taxid = df2.loc[row, "taxid"]
        handle = Entrez.esearch(
            db="assembly",
            term=f"txid{taxid}[Organism]",
            retmax=100
        )
        record = Entrez.read(handle)
        handle.close()

        assembly_ids = record["IdList"]

        if not assembly_ids:
            handle = Entrez.esearch(
                    db="assembly",
                    term=f"{taxid}[uid]",
                    retmax=100
                )
            record = Entrez.read(handle)
            handle.close()

            assembly_ids = record["IdList"]

        assembly_ids = record["IdList"]

        if not assembly_ids:
            print(f"No assemblies found for taxid {taxid}")
            continue

        handle = Entrez.esummary(
            db="assembly", 
            id=",".join(assembly_ids), 
            retmax=100
            )

        summaries = Entrez.read(handle)
        handle.close()

        accession_numbers = [summary["AssemblyAccession"] for summary in summaries["DocumentSummarySet"]["DocumentSummary"]]
        
        print(f"\n\ninfo for {taxid}: {summaries['DocumentSummarySet']['DocumentSummary']}\n\n")

        print(f"taxid: {taxid} | accession numbers: {accession_numbers}")
        time.sleep(0.5) # Pause for 0.5 seconds to avoid overwhelming the server
    
    ##### Todo
        # Determine which accession is the reference? in the loop.
        # Save reference accession to DF2.
        # ...
    
get_assembly(df_b, dataset="B")

info for 137743: [DictElement({'RsUid': '', 'GbUid': '69715418', 'AssemblyAccession': 'GCA_047301825.1', 'LastMajorReleaseAccession': 'GCA_047301825.1', 'LatestAccession': '', 'ChainId': '47301825', 'AssemblyName': 'ASM4730182v1', 'UCSCName': '', 'EnsemblName': '', 'Taxid': '137743', 'Organism': 'Abortiporus biennis (blushing rosette)', 'SpeciesTaxid': '137743', 'SpeciesName': 'Abortiporus biennis', 'AssemblyType': 'haploid', 'AssemblyStatus': 'Contig', 'AssemblyStatusSort': '6', 'WGS': 'JBEIAH01', 'GB_BioProjects': [{'BioprojectAccn': 'PRJNA1117344', 'BioprojectId': '1117344'}], 'GB_Projects': [], 'RS_BioProjects': [], 'RS_Projects': [], 'BioSampleAccn': 'SAMN41564068', 'BioSampleId': '41564068', 'Biosource': {'InfraspeciesList': [{'Sub_type': 'strain', 'Sub_value': 'LGAM 436'}], 'Sex': '', 'Isolate': ''}, 'Coverage': '135', 'PartialGenomeRepresentation': 'false', 'Primary': '69715388', 'AssemblyDescription': '', 'ReleaseLevel': 'Major', 'ReleaseType': 'Major', 'AsmReleaseDate_GenBank': '2025/01/29 00:00', 'AsmReleaseDate_RefSeq': '1/01/01 00:00', 'SeqReleaseDate': '2025/01/29 00:00', 'AsmUpdateDate': '2025/01/29 00:00', 'SubmissionDate': '2025/01/29 00:00', 'LastUpdateDate': '2025/01/29 00:00', 'SubmitterOrganization': 'National Technical University of Athens (NTUA)', 'RefSeq_category': 'na', 'AnomalousList': [], 'ExclFromRefSeq': [], 'PropertyList': ['full-genome-representation', 'genbank_has_annotation', 'has_annotation', 'latest', 'latest_genbank', 'wgs'], 'FromType': '', 'Synonym': {'Genbank': 'GCA_047301825.1', 'RefSeq': '', 'Similarity': ''}, 'ContigN50': '110047', 'ScaffoldN50': '110047', 'AnnotRptUrl': '', 'FtpPath_GenBank': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1', 'FtpPath_RefSeq': '', 'FtpPath_Assembly_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1/GCA_047301825.1_ASM4730182v1_assembly_report.txt', 'FtpPath_Stats_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1/GCA_047301825.1_ASM4730182v1_assembly_stats.txt', 'FtpPath_Regions_rpt': '', 'Busco': {'RefSeqAnnotationRelease': '', 'BuscoLineage': '', 'BuscoVer': '', 'Complete': '', 'SingleCopy': '', 'Duplicated': '', 'Fragmented': '', 'Missing': '', 'TotalCount': '0'}, 'SortOrder': '5C6XBEBB9998899520473018259800', 'Meta': ' <Stats> <Stat category="alt_loci_count" sequence_tag="all">0</Stat> <Stat category="chromosome_count" sequence_tag="all">0</Stat> <Stat category="contig_count" sequence_tag="all">808</Stat> <Stat category="contig_l50" sequence_tag="all">85</Stat> <Stat category="contig_n50" sequence_tag="all">110047</Stat> <Stat category="non_chromosome_replicon_count" sequence_tag="all">0</Stat> <Stat category="replicon_count" sequence_tag="all">0</Stat> <Stat category="scaffold_count" sequence_tag="all">808</Stat> <Stat category="scaffold_count" sequence_tag="placed">0</Stat> <Stat category="scaffold_count" sequence_tag="unlocalized">0</Stat> <Stat category="scaffold_count" sequence_tag="unplaced">808</Stat> <Stat category="scaffold_l50" sequence_tag="all">85</Stat> <Stat category="scaffold_n50" sequence_tag="all">110047</Stat> <Stat category="total_length" sequence_tag="all">33729601</Stat> <Stat category="ungapped_length" sequence_tag="all">33729601</Stat> </Stats> <FtpSites>   <FtpPath type="Assembly_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1/GCA_047301825.1_ASM4730182v1_assembly_report.txt</FtpPath>   <FtpPath type="GenBank">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1</FtpPath>   <FtpPath type="Stats_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/047/301/825/GCA_047301825.1_ASM4730182v1/GCA_047301825.1_ASM4730182v1_assembly_stats.txt</FtpPath> </FtpSites> <assembly-level>1</assembly-level> <assembly-status>Contig</assembly-status> <representative-status>na</representative-status> <submitter-organization>National Technical University of Athens (NTUA)</submitter-organization>    '}, attributes={'uid': '26937651'}), DictElement({'RsUid': '', 'GbUid': '32317688', 'AssemblyAccession': 'GCA_022606235.1', 'LastMajorReleaseAccession': 'GCA_022606235.1', 'LatestAccession': '', 'ChainId': '22606235', 'AssemblyName': 'Abobie1', 'UCSCName': '', 'EnsemblName': '', 'Taxid': '137743', 'Organism': 'Abortiporus biennis (blushing rosette)', 'SpeciesTaxid': '137743', 'SpeciesName': 'Abortiporus biennis', 'AssemblyType': 'haploid', 'AssemblyStatus': 'Contig', 'AssemblyStatusSort': '6', 'WGS': 'JABYQP01', 'GB_BioProjects': [{'BioprojectAccn': 'PRJNA444028', 'BioprojectId': '444028'}], 'GB_Projects': [], 'RS_BioProjects': [], 'RS_Projects': [], 'BioSampleAccn': 'SAMN08777216', 'BioSampleId': '8777216', 'Biosource': {'InfraspeciesList': [{'Sub_type': 'strain', 'Sub_value': 'CIRM-BRFM 1778'}], 'Sex': '', 'Isolate': ''}, 'Coverage': '49.44', 'PartialGenomeRepresentation': 'false', 'Primary': '32317678', 'AssemblyDescription': '', 'ReleaseLevel': 'Major', 'ReleaseType': 'Major', 'AsmReleaseDate_GenBank': '2022/03/17 00:00', 'AsmReleaseDate_RefSeq': '1/01/01 00:00', 'SeqReleaseDate': '2022/03/16 00:00', 'AsmUpdateDate': '2022/03/17 00:00', 'SubmissionDate': '2022/03/16 00:00', 'LastUpdateDate': '2022/03/17 00:00', 'SubmitterOrganization': 'DOE Joint Genome Institute', 'RefSeq_category': 'reference genome', 'AnomalousList': [], 'ExclFromRefSeq': [], 'PropertyList': ['full-genome-representation', 'genbank_has_annotation', 'has_annotation', 'latest', 'latest_genbank', 'reference', 'wgs'], 'FromType': '', 'Synonym': {'Genbank': 'GCA_022606235.1', 'RefSeq': '', 'Similarity': ''}, 'ContigN50': '721010', 'ScaffoldN50': '721010', 'AnnotRptUrl': '', 'FtpPath_GenBank': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1', 'FtpPath_RefSeq': '', 'FtpPath_Assembly_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1/GCA_022606235.1_Abobie1_assembly_report.txt', 'FtpPath_Stats_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1/GCA_022606235.1_Abobie1_assembly_stats.txt', 'FtpPath_Regions_rpt': '', 'Busco': {'RefSeqAnnotationRelease': '', 'BuscoLineage': '', 'BuscoVer': '', 'Complete': '', 'SingleCopy': '', 'Duplicated': '', 'Fragmented': '', 'Missing': '', 'TotalCount': '0'}, 'SortOrder': '1C6XBEBB9992789890226062359800', 'Meta': ' <Stats> <Stat category="alt_loci_count" sequence_tag="all">0</Stat> <Stat category="chromosome_count" sequence_tag="all">0</Stat> <Stat category="contig_count" sequence_tag="all">73</Stat> <Stat category="contig_l50" sequence_tag="all">16</Stat> <Stat category="contig_n50" sequence_tag="all">721010</Stat> <Stat category="non_chromosome_replicon_count" sequence_tag="all">0</Stat> <Stat category="replicon_count" sequence_tag="all">0</Stat> <Stat category="scaffold_count" sequence_tag="all">73</Stat> <Stat category="scaffold_count" sequence_tag="placed">0</Stat> <Stat category="scaffold_count" sequence_tag="unlocalized">0</Stat> <Stat category="scaffold_count" sequence_tag="unplaced">73</Stat> <Stat category="scaffold_l50" sequence_tag="all">16</Stat> <Stat category="scaffold_n50" sequence_tag="all">721010</Stat> <Stat category="total_length" sequence_tag="all">33118568</Stat> <Stat category="ungapped_length" sequence_tag="all">33118568</Stat> </Stats> <FtpSites>   <FtpPath type="Assembly_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1/GCA_022606235.1_Abobie1_assembly_report.txt</FtpPath>   <FtpPath type="GenBank">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1</FtpPath>   <FtpPath type="Stats_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/022/606/235/GCA_022606235.1_Abobie1/GCA_022606235.1_Abobie1_assembly_stats.txt</FtpPath> </FtpSites> <assembly-level>1</assembly-level> <assembly-status>Contig</assembly-status> <representative-status>reference genome</representative-status> <submitter-organization>DOE Joint Genome Institute</submitter-organization>    '}, attributes={'uid': '12336801'})]


taxid: 137743 | accession numbers: ['GCA_047301825.1', 'GCA_022606235.1']


info for 420591: [DictElement({'RsUid': '2188218', 'GbUid': '1983758', 'AssemblyAccession': 'GCF_001166685.1', 'LastMajorReleaseAccession': 'GCF_001166685.1', 'LatestAccession': '', 'ChainId': '1166685', 'AssemblyName': '5392_6#7', 'UCSCName': '', 'EnsemblName': '', 'Taxid': '1313', 'Organism': 'Streptococcus pneumoniae (firmicutes)', 'SpeciesTaxid': '1313', 'SpeciesName': 'Streptococcus pneumoniae', 'AssemblyType': 'haploid', 'AssemblyStatus': 'Scaffold', 'AssemblyStatusSort': '6', 'WGS': 'CPKF01', 'GB_BioProjects': [{'BioprojectAccn': 'PRJEB2255', 'BioprojectId': '204075'}], 'GB_Projects': [], 'RS_BioProjects': [{'BioprojectAccn': 'PRJNA224116', 'BioprojectId': '224116'}], 'RS_Projects': [], 'BioSampleAccn': 'SAMEA682566', 'BioSampleId': '113132', 'Biosource': {'InfraspeciesList': [{'Sub_type': 'serovar', 'Sub_value': '6B'}, {'Sub_type': 'strain', 'Sub_value': 'spnIC178'}], 'Sex': '', 'Isolate': ''}, 'Coverage': '100', 'PartialGenomeRepresentation': 'false', 'Primary': '2188208', 'AssemblyDescription': '', 'ReleaseLevel': 'Major', 'ReleaseType': 'Major', 'AsmReleaseDate_GenBank': '2015/07/19 00:00', 'AsmReleaseDate_RefSeq': '2015/08/06 00:00', 'SeqReleaseDate': '2015/07/15 00:00', 'AsmUpdateDate': '2026/04/27 00:00', 'SubmissionDate': '2015/07/15 00:00', 'LastUpdateDate': '2026/04/27 00:00', 'SubmitterOrganization': 'SC', 'RefSeq_category': 'na', 'AnomalousList': [], 'ExclFromRefSeq': [], 'PropertyList': ['full-genome-representation', 'genbank_has_annotation', 'has_annotation', 'latest', 'latest_genbank', 'latest_refseq', 'refseq_has_annotation', 'wgs'], 'FromType': '', 'Synonym': {'Genbank': 'GCA_001166685.1', 'RefSeq': 'GCF_001166685.1', 'Similarity': 'identical'}, 'ContigN50': '53254', 'ScaffoldN50': '53254', 'AnnotRptUrl': '', 'FtpPath_GenBank': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/166/685/GCA_001166685.1_5392_6_7', 'FtpPath_RefSeq': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7', 'FtpPath_Assembly_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7/GCF_001166685.1_5392_6_7_assembly_report.txt', 'FtpPath_Stats_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7/GCF_001166685.1_5392_6_7_assembly_stats.txt', 'FtpPath_Regions_rpt': '', 'Busco': {'RefSeqAnnotationRelease': '', 'BuscoLineage': '', 'BuscoVer': '', 'Complete': '', 'SingleCopy': '', 'Duplicated': '', 'Fragmented': '', 'Missing': '', 'TotalCount': '0'}, 'SortOrder': '5C6X24329999467450011666859898', 'Meta': ' <Stats> <Stat category="alt_loci_count" sequence_tag="all">0</Stat> <Stat category="chromosome_count" sequence_tag="all">0</Stat> <Stat category="contig_count" sequence_tag="all">75</Stat> <Stat category="contig_l50" sequence_tag="all">15</Stat> <Stat category="contig_n50" sequence_tag="all">53254</Stat> <Stat category="non_chromosome_replicon_count" sequence_tag="all">0</Stat> <Stat category="replicon_count" sequence_tag="all">0</Stat> <Stat category="scaffold_count" sequence_tag="all">72</Stat> <Stat category="scaffold_count" sequence_tag="placed">0</Stat> <Stat category="scaffold_count" sequence_tag="unlocalized">0</Stat> <Stat category="scaffold_count" sequence_tag="unplaced">72</Stat> <Stat category="scaffold_l50" sequence_tag="all">15</Stat> <Stat category="scaffold_n50" sequence_tag="all">53254</Stat> <Stat category="total_length" sequence_tag="all">2177362</Stat> <Stat category="ungapped_length" sequence_tag="all">2176883</Stat> </Stats> <FtpSites>   <FtpPath type="Assembly_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7/GCF_001166685.1_5392_6_7_assembly_report.txt</FtpPath>   <FtpPath type="GenBank">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/166/685/GCA_001166685.1_5392_6_7</FtpPath>   <FtpPath type="RefSeq">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7</FtpPath>   <FtpPath type="Stats_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/166/685/GCF_001166685.1_5392_6_7/GCF_001166685.1_5392_6_7_assembly_stats.txt</FtpPath> </FtpSites> <assembly-level>8</assembly-level> <assembly-status>Scaffold</assembly-status> <representative-status>na</representative-status> <submitter-organization>SC</submitter-organization> <taxonomy-check-status>OK</taxonomy-check-status>    '}, attributes={'uid': '420591'})]


taxid: 420591 | accession numbers: ['GCF_001166685.1']
No assemblies found for taxid 327746
No assemblies found for taxid 101563


info for 327741: [DictElement({'RsUid': '1752318', 'GbUid': '1743548', 'AssemblyAccession': 'GCF_000983835.1', 'LastMajorReleaseAccession': 'GCF_000983835.1', 'LatestAccession': '', 'ChainId': '983835', 'AssemblyName': 'PA014', 'UCSCName': '', 'EnsemblName': '', 'Taxid': '54388', 'Organism': 'Salmonella enterica subsp. enterica serovar Paratyphi A (enterobacteria)', 'SpeciesTaxid': '28901', 'SpeciesName': 'Salmonella enterica', 'AssemblyType': 'haploid', 'AssemblyStatus': 'Scaffold', 'AssemblyStatusSort': '6', 'WGS': 'CCLZ01', 'GB_BioProjects': [{'BioprojectAccn': 'PRJEB5558', 'BioprojectId': '282201'}], 'GB_Projects': [], 'RS_BioProjects': [{'BioprojectAccn': 'PRJNA224116', 'BioprojectId': '224116'}], 'RS_Projects': [], 'BioSampleAccn': 'SAMEA2646073', 'BioSampleId': '3568702', 'Biosource': {'InfraspeciesList': [{'Sub_type': 'serovar', 'Sub_value': 'Paratyphi A'}], 'Sex': '', 'Isolate': ''}, 'Coverage': '161', 'PartialGenomeRepresentation': 'false', 'Primary': '1752308', 'AssemblyDescription': '', 'ReleaseLevel': 'Major', 'ReleaseType': 'Major', 'AsmReleaseDate_GenBank': '2015/04/30 00:00', 'AsmReleaseDate_RefSeq': '2015/05/06 00:00', 'SeqReleaseDate': '2015/04/25 00:00', 'AsmUpdateDate': '2026/03/15 00:00', 'SubmissionDate': '2015/04/25 00:00', 'LastUpdateDate': '2026/03/15 00:00', 'SubmitterOrganization': 'UNIVERSITY OF WARWICK', 'RefSeq_category': 'na', 'AnomalousList': [], 'ExclFromRefSeq': ['missing strain identifier'], 'PropertyList': ['excluded-from-refseq', 'full-genome-representation', 'genbank_has_annotation', 'has_annotation', 'latest', 'latest_genbank', 'refseq_has_annotation', 'suppressed_refseq', 'wgs'], 'FromType': '', 'Synonym': {'Genbank': 'GCA_000983835.1', 'RefSeq': 'GCF_000983835.1', 'Similarity': 'identical'}, 'ContigN50': '201702', 'ScaffoldN50': '4496518', 'AnnotRptUrl': '', 'FtpPath_GenBank': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/983/835/GCA_000983835.1_PA014', 'FtpPath_RefSeq': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014', 'FtpPath_Assembly_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014/GCF_000983835.1_PA014_assembly_report.txt', 'FtpPath_Stats_rpt': 'ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014/GCF_000983835.1_PA014_assembly_stats.txt', 'FtpPath_Regions_rpt': '', 'Busco': {'RefSeqAnnotationRelease': '', 'BuscoLineage': '', 'BuscoVer': '', 'Complete': '', 'SingleCopy': '', 'Duplicated': '', 'Fragmented': '', 'Missing': '', 'TotalCount': '0'}, 'SortOrder': '9C6X0EAF9997982970009838359898', 'Meta': ' <Stats> <Stat category="alt_loci_count" sequence_tag="all">0</Stat> <Stat category="chromosome_count" sequence_tag="all">0</Stat> <Stat category="contig_count" sequence_tag="all">157</Stat> <Stat category="contig_l50" sequence_tag="all">9</Stat> <Stat category="contig_n50" sequence_tag="all">201702</Stat> <Stat category="non_chromosome_replicon_count" sequence_tag="all">0</Stat> <Stat category="replicon_count" sequence_tag="all">0</Stat> <Stat category="scaffold_count" sequence_tag="all">2</Stat> <Stat category="scaffold_count" sequence_tag="placed">0</Stat> <Stat category="scaffold_count" sequence_tag="unlocalized">0</Stat> <Stat category="scaffold_count" sequence_tag="unplaced">2</Stat> <Stat category="scaffold_l50" sequence_tag="all">1</Stat> <Stat category="scaffold_n50" sequence_tag="all">4496518</Stat> <Stat category="total_length" sequence_tag="all">4602643</Stat> <Stat category="ungapped_length" sequence_tag="all">4587483</Stat> </Stats> <FtpSites>   <FtpPath type="Assembly_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014/GCF_000983835.1_PA014_assembly_report.txt</FtpPath>   <FtpPath type="GenBank">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/983/835/GCA_000983835.1_PA014</FtpPath>   <FtpPath type="RefSeq">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014</FtpPath>   <FtpPath type="Stats_rpt">ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/983/835/GCF_000983835.1_PA014/GCF_000983835.1_PA014_assembly_stats.txt</FtpPath> </FtpSites> <assembly-level>8</assembly-level> <assembly-status>Scaffold</assembly-status> <representative-status>na</representative-status> <submitter-organization>UNIVERSITY OF WARWICK</submitter-organization> <taxonomy-check-status>OK</taxonomy-check-status>    '}, attributes={'uid': '327741'})]


taxid: 327741 | accession numbers: ['GCF_000983835.1']



In [7]:
df2.head()

,organism,domain,temperature,taxid,lineage_text,superkingdom,phylum,class,order,family,genus
4,abortiporus_biennis,Eukaryota,26,137743,cellular organisms; Eukaryota; Opisthokonta; F...,2759,5204.0,155619.0,5303.0,83233.0,137742.0
5,absidia_anomala,Eukaryota,24,420591,cellular organisms; Eukaryota; Opisthokonta; F...,2759,1913637.0,NaN,4827.0,4851.0,4828.0
6,absidia_atrospora,Eukaryota,26,327746,cellular organisms; Eukaryota; Opisthokonta; F...,2759,1913637.0,NaN,4827.0,499202.0,688353.0
7,absidia_blakesleeana,Eukaryota,25,101563,cellular organisms; Eukaryota; Opisthokonta; F...,2759,1913637.0,NaN,4827.0,499202.0,688353.0
8,absidia_californica,Eukaryota,24,327741,cellular organisms; Eukaryota; Opisthokonta; F...,2759,1913637.0,NaN,4827.0,4851.0,4828.0

In [5]:
####### REMOVE DUPLICATES FROM COMBINED CSV #######

# drop duplicates where assemby AND temperature are the same.
# assembly#,[28,27,26], [A, B, C], trna#
# assembly#,[24], [B], trna#

KeyError: 0

In [ ]:

# get fasta files
# unzip fasta
# barrnap fasta file for quality.
# get tRNA & save it in df
# scrape web for it????
is_quality = []
quality_scores = []
quality_means = []
trna_fasta = []

for row in range(1):
    assembly = df.at[row, 'Assembly']
    url = f"https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/{assembly}/download?include_annotation_type=GENOME_FASTA"
    res = requests.get(url)  # this returns a zip folder

    # Define the filename for the downloaded zip file
    zip_filename = f"{assembly}.zip"
    # Save the zip file
    with open(zip_filename, 'wb') as f:
        for chunk in res.iter_content(chunk_size=8192):
            f.write(chunk)
    extract_dir = f"{assembly}_dir"
    if not f"{extract_dir}":
        os.mkdir(extract_dir)

    with ZipFile(zip_filename, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    
    # Name path of the extracted folder
    fasta_path = f"{extract_dir}/ncbi_dataset/data/{assembly}"

    fasta_file = os.listdir(fasta_path)[0] # => []
    # Run pybarrnap rRNA prediction
    barrnap = Barrnap(
        fasta_path + "/" + fasta_file,
        evalue=1e-6,
        lencutoff=0.8,
        reject=0.25,
        threads=1,
        kingdom="euk",
        accurate=False,
        quiet=False,
    )
    result = barrnap.run()
    # Get rRNA GFF text and print
    # print("\n========== Print rRNA GFF ==========")
    gff_text = result.get_gff_text()
    gff_text1 = [lines for lines in gff_text.split("\n")]
    gff_nums = [
        float(item.split("\t")[5]) for item in gff_text1[1:] if len(item.split('\t'))>6
        ]
    gff_mean = mean(gff_nums)
    print(gff_text)
    print(f"gff_mean: {gff_mean}")

    # Get rRNA features and print
    print("\n========== Print rRNA features ==========")
    genes_set = set()
    needed_genes = {"5S", "5_8S", "18S", "28S"}
    for rec in result.seq_records: # seq_records is a list
        print(rec)
        for feature in rec.features: # features on rec is a list
            qualifiers = feature.qualifiers #feature.id, feature.type, feature.location, feature.qualifiers)
            if "gene" in qualifiers:
                for g in qualifiers["gene"]:
                    genes_set.add(g)

    return_value = None # Quality Metric
    if all([any([needed in g for g in genes_set]) for needed in needed_genes]):
        
        return_value = True
        quality_nums = gff_nums
        quality_mean = gff_mean
    else:
        return_value = False
        quality_nums = nan
        quality_mean = nan
    
    # counted number of tRNA 

    fasta_full_path = fasta_path + "/" + fasta_file
    output_name = f"{fasta_file}_trna.fasta"
    # produces fasta file with tRNA sequences in {output_name}
    !tRNAscan-SE {fasta_full_path} --fasta {output_name}
    # Now we need to process the fasta file to get the tRNA sequences 
    # and save them in the dataframe or a separate file as needed.  

    is_quality.append(return_value)
    quality_scores.append(quality_nums)
    quality_means.append(quality_mean)
    trna_fasta.append(output_name)
            # qaul_genes = []
            # all three types had to be identified
            # must = '5S', '5_8S', '18S', '28S'

    # Do stuff here with the Fasta file!
    # ✔️ Pybarrnap
    # ✔️ Create a quality metric & save to df
    # ✔️ Save quality metric to df
    # 
    # ✔️ Find tRNA from the fasta
    # Save tRNA to df (with linebreaks included, pre-process before CNN) 

    %pwd
    %ls
    %rm -rf {extract_dir}
    %rm {zip_filename}
    
    print("\n")
    print(f"{'='*10}")
    print("\n")
    %ls
    # !ncbi-genome-download --section genbank --assembly-accessions {assembly} --formats fasta fungi

2026-08-12 16:22:25 | INFO | Run pybarrnap v0.5.2
2026-08-12 16:22:25 | INFO | Operating System: linux
2026-08-12 16:22:25 | INFO | Python Version: v3.13.14
2026-08-12 16:22:25 | INFO | Check Dependencies: pyhmmer v0.12.1 is installed
2026-08-12 16:22:25 | INFO | Check Dependencies: biopython v1.87 is installed
2026-08-12 16:22:25 | INFO | Set Option: evalue=1e-06
2026-08-12 16:22:25 | INFO | Set Option: lencutoff=0.8
2026-08-12 16:22:25 | INFO | Set Option: reject=0.25
2026-08-12 16:22:25 | INFO | Set Option: threads=1
2026-08-12 16:22:25 | INFO | Set Option: kingdom='euk'
2026-08-12 16:22:25 | INFO | Set Option: accurate=False
2026-08-12 16:22:25 | INFO | Number of Target Sequence = 4
2026-08-12 16:22:25 | INFO | Seq1. name='CU329670.1', length=5,579,133, description='CU329670.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: I'
2026-08-12 16:22:25 | INFO | Seq2. name='CU329671.1', length=4,539,804, description='CU329671.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: II'
2026-08-12 16:22:25 | INFO | Seq3. name='CU329672.1', length=2,452,883, description='CU329672.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: III'
2026-08-12 16:22:25 | INFO | Seq4. name='X54421.1', length=19,431, description='X54421.1 Schizosaccharomyces pombe complete mitochondrial genome'
2026-08-12 16:22:25 | INFO | Use HMM DB: /home/nkmwicz/micromamba/envs/fungi/lib/python3.13/site-packages/pybarrnap/db/hmm/euk.hmm
2026-08-12 16:22:25 | INFO | Running pyhmmer.nhmmer...
2026-08-12 16:22:49 | INFO | Found: 18S_rRNA CU329672.1 2440995..2442834(+) L=1840/1869(98.45%)
2026-08-12 16:22:49 | INFO | Found: 18S_rRNA CU329672.1 10420..12259(-) L=1840/1869(98.45%)
2026-08-12 16:22:49 | INFO | Found: 18S_rRNA CU329672.1 21290..23129(-) L=1840/1869(98.45%)
2026-08-12 16:22:49 | INFO | Found: 18S_rRNA CU329672.1 16..1389(-) L=1374/1869(73.52%)
2026-08-12 16:22:49 | INFO | Found: 18S_rRNA CU329672.1 2451884..2452883(+) L=1000/1869(53.50%)
2026-08-12 16:22:49 | INFO | Found: 28S_rRNA CU329672.1 2443717..2447209(+) L=3493/2912(119.95%)
2026-08-12 16:22:49 | INFO | Found: 28S_rRNA CU329672.1 6045..9537(-) L=3493/2912(119.95%)
2026-08-12 16:22:49 | INFO | Found: 28S_rRNA CU329672.1 16915..20407(-) L=3493/2912(119.95%)
2026-08-12 16:22:49 | INFO | Reject: 28S_rRNA CU329672.1 814799..814943(+) L=145/2912(4.98%)
2026-08-12 16:22:49 | INFO | Reject: 28S_rRNA X54421.1 2278..2466(+) L=189/2912(6.49%)
2026-08-12 16:22:49 | INFO | Reject: 28S_rRNA X54421.1 1562..1767(+) L=206/2912(7.07%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 1690947..1691061(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 1474261..1474375(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 456529..456643(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 149660..149774(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 2976821..2976935(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 3165398..3165512(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 3634373..3634487(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 3830382..3830496(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 4184357..4184471(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 4240852..4240966(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 464529..464643(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 520305..520419(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 783261..783375(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 1199929..1200043(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 1406587..1406701(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 1504375..1504489(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 2032412..2032526(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 3938580..3938694(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 2261373..2261487(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 4210383..4210497(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 523319..523433(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 926144..926258(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 1702126..1702240(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 853316..853430(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 1370036..1370150(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329672.1 2308168..2308282(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 3891665..3891779(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 912232..912346(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 1563477..1563591(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 2322735..2322849(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 569153..569267(+) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 2442703..2442817(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 4161625..4161735(-) L=111/119(93.28%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329670.1 3547902..3548016(-) L=115/119(96.64%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 3171574..3171678(-) L=105/119(88.24%)
2026-08-12 16:22:49 | INFO | Found: 5S_rRNA CU329671.1 3096971..3097072(-) L=102/119(85.71%)
2026-08-12 16:22:49 | INFO | Found: 5_8S_rRNA CU329672.1 2443257..2443409(+) L=153/156(98.08%)
2026-08-12 16:22:49 | INFO | Found: 5_8S_rRNA CU329672.1 9845..9997(-) L=153/156(98.08%)
2026-08-12 16:22:49 | INFO | Found: 5_8S_rRNA CU329672.1 20715..20867(-) L=153/156(98.08%)
2026-08-12 16:22:49 | INFO | Found 47 ribosomal RNA features

##gff-version 3
CU329670.1	pybarrnap:0.5.2	rRNA	149660	149774	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	456529	456643	4.7e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	912232	912346	1.9e-21	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	1563477	1563591	2.1e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	2976821	2976935	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	3165398	3165512	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	3547902	3548016	7.9e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	3634373	3634487	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	3830382	3830496	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	3891665	3891779	7.9e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	4184357	4184471	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.2	rRNA	4240852	4240966	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	464529	464643	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	520305	520419	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	569153	569267	1.0e-20	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	783261	783375	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	1199929	1200043	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	1406587	1406701	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	1504375	1504489	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	2032412	2032526	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	2261373	2261487	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	2322735	2322849	2.8e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	2442703	2442817	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	3096971	3097072	1.2e-07	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	3171574	3171678	3.1e-12	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	3938580	3938694	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	4161625	4161735	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.2	rRNA	4210383	4210497	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	16	1389	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 73.52 percent of the 18S ribosomal RNA
CU329672.1	pybarrnap:0.5.2	rRNA	6045	9537	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.2	rRNA	9845	9997	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.2	rRNA	10420	12259	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.2	rRNA	16915	20407	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.2	rRNA	20715	20867	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.2	rRNA	21290	23129	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.2	rRNA	523319	523433	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	853316	853430	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	926144	926258	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	1370036	1370150	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	1474261	1474375	4.4e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	1690947	1691061	4.4e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	1702126	1702240	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	2308168	2308282	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.2	rRNA	2440995	2442834	0	+	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.2	rRNA	2443257	2443409	6.7e-45	+	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.2	rRNA	2443717	2447209	0	+	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.2	rRNA	2451884	2452883	1.3e-272	+	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 53.50 percent of the 18S ribosomal RNA

gff_mean: 2.553257446811402e-09

========== Print rRNA features ==========
ID: CU329670.1
Name: CU329670.1
Description: CU329670.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: I
Number of features: 12
Seq('GATCACGTACATCACCTTGTAAGAATTTATCTGCAATAGTCCTTCGGTATTGTA...ATC')
ID: CU329671.1
Name: CU329671.1
Description: CU329671.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: II
Number of features: 16
Seq('GATCTCGCAACTCTTAATAAAGCTAATTCCTGCTAATTCGCTATACACTAAATC...TTT')
ID: CU329672.1
Name: CU329672.1
Description: CU329672.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: III
Number of features: 19
Seq('GATCAGCCAAAATGGCTGATCCAGCTATTTAGCAGGTTAAGGTCTCGTTCGTTA...GGG')
ID: X54421.1
Name: X54421.1
Description: X54421.1 Schizosaccharomyces pombe complete mitochondrial genome
Number of features: 0
Seq('AATGTGTAATTTGAATCAATTTCTATCCTTTTAAAAATACATCATAAAGTGTAC...TGT')

tRNAscan-SE v.2.0.13 (Jul 2026) - scan sequences for transfer RNAs
Copyright (C) 2026 Patricia Chan and Todd Lowe
                   University of California Santa Cruz
Freely distributed under the GNU General Public License (GPLv3)

------------------------------------------------------------
Sequence file(s) to search:        GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_ASM294v2_genomic.fna
Search Mode:                       Eukaryotic
Results written to:                Standard output
Output format:                     Tabular
Searching with:                    Infernal First Pass->Infernal
Isotype-specific model scan:       Yes
Covariance model:                  /home/nkmwicz/micromamba/envs/fungi/lib/tRNAscan-SE/models/TRNAinf-euk.cm
                                   /home/nkmwicz/micromamba/envs/fungi/lib/tRNAscan-SE/models/TRNAinf-euk-SeC.cm
Infernal first pass cutoff score:  10

Temporary directory:               /tmp
Predicted tRNA sequences
    saved to:                      GCA_000002945.2_ASM294v2_genomic.fna_trna.fasta
------------------------------------------------------------

Status: Phase I: Searching for tRNAs with HMM-enabled Infernal
Status: Phase II: Infernal verification of candidate tRNAs detected with first-pass scan
Sequence   		tRNA   	Bounds 	tRNA	Anti	Intron Bounds	Inf
Name       	tRNA #	Begin  	End    	Type	Codon	Begin	End	Score	Note
--------   	------	-----  	------ 	----	-----	-----	----	------	------
CU329670.1 	1	365155 	365226 	Pro	TGG	0	0	68.8
CU329670.1 	2	446000 	446071 	Val	CAC	0	0	64.9
CU329670.1 	3	957183 	957254 	Glu	TTC	0	0	58.7
CU329670.1 	4	1096369	1096466	Ser	CGA	1096406	1096421	76.5
CU329670.1 	5	1096474	1096545	iMet	CAT	0	0	54.9
CU329670.1 	6	1421149	1421221	Cys	GCA	0	0	68.1
CU329670.1 	7	1704582	1704664	Lys	CTT	1704621	1704628	74.7
CU329670.1 	8	1746464	1746547	Tyr	GTA	1746502	1746511	62.3
CU329670.1 	9	1772296	1772369	Ile	AAT	0	0	61.7
CU329670.1 	10	2433048	2433119	Thr	AGT	0	0	79.6
CU329670.1 	11	2441963	2442037	Lys	TTT	0	0	72.9
CU329670.1 	12	2510538	2510610	Cys	GCA	0	0	65.9
CU329670.1 	13	2578426	2578524	Ile	TAT	2578464	2578488	57.4
CU329670.1 	14	3086310	3086392	Lys	CTT	3086349	3086356	74.7
CU329670.1 	15	3157430	3157501	Ala	TGC	0	0	70.6
CU329670.1 	16	3164749	3164820	Thr	CGT	0	0	72.2
CU329670.1 	17	3443055	3443144	Arg	CCG	3443091	3443108	38.5
CU329670.1 	18	3591948	3592044	Leu	TAG	3591985	3592002	46.1
CU329670.1 	19	3700665	3700737	Cys	GCA	0	0	68.1
CU329670.1 	20	3701556	3701628	Phe	GAA	0	0	69.0
CU329670.1 	21	3736520	3736592	Arg	ACG	0	0	71.4
CU329670.1 	22	3768290	3768363	Ile	AAT	0	0	65.0
CU329670.1 	23	3776768	3776839	Glu	CTC	0	0	68.9
CU329670.1 	24	3777192	3777265	Ala	AGC	0	0	57.1
CU329670.1 	25	4265149	4265245	Ser	TGA	4265186	4265200	77.3
CU329670.1 	26	4265253	4265324	iMet	CAT	0	0	54.9
CU329670.1 	27	4532857	4532927	Asp	GTC	0	0	61.0
CU329670.1 	28	4715431	4715502	Thr	AGT	0	0	79.6
CU329670.1 	29	4796977	4797059	Ala	CGC	4797013	4797023	68.5
CU329670.1 	30	5437747	5437828	Ser	AGA	0	0	79.7
CU329670.1 	31	5232987	5232917	Asp	GTC	0	0	61.0
CU329670.1 	32	5045204	5045132	Arg	ACG	0	0	71.4
CU329670.1 	33	4059106	4059028	Leu	AAG	0	0	51.5
CU329670.1 	34	3773983	3773910	Ile	AAT	0	0	65.0
CU329670.1 	35	3765505	3765434	Glu	CTC	0	0	68.9
CU329670.1 	36	3765081	3765008	Ala	AGC	0	0	57.1
CU329670.1 	37	3752406	3752334	Phe	GAA	0	0	69.0
CU329670.1 	38	3710821	3710739	Val	AAC	3710783	3710775	58.5
CU329670.1 	39	3559826	3559754	Trp	CCA	0	0	69.1
CU329670.1 	40	3047758	3047677	Ser	AGA	0	0	79.7
CU329670.1 	41	2844745	2844674	Thr	AGT	0	0	80.6
CU329670.1 	42	2802858	2802761	Leu	TAA	2802820	2802805	47.5
CU329670.1 	43	2684765	2684683	Lys	CTT	2684726	2684719	74.7
CU329670.1 	44	2249250	2249180	Gly	GCC	0	0	71.4
CU329670.1 	45	2214814	2214733	Val	AAC	2214776	2214769	58.6
CU329670.1 	46	1733838	1733764	Lys	TTT	0	0	72.9
CU329670.1 	47	1646362	1646292	Gly	GCC	0	0	71.4
CU329670.1 	48	1603376	1603305	Thr	AGT	0	0	79.6
CU329670.1 	49	1527181	1527088	Leu	CAG	1527143	1527134	67.1
CU329670.1 	50	1485061	1484979	Met	CAT	1485023	1485015	57.1
CU329670.1 	51	1449469	1449398	Pro	AGG	0	0	61.8
CU329670.1 	52	1315020	1314924	Pro	CGG	1314983	1314960	49.7
CU329670.1 	53	1195663	1195592	Ala	TGC	0	0	70.6
CU329670.1 	54	934738 	934665 	Ala	AGC	0	0	57.1
CU329670.1 	55	718190 	718119 	Glu	TTC	0	0	58.7
CU329670.1 	56	703147 	703075 	Val	TAC	0	0	72.1
CU329671.1 	1	257454 	257525 	Gln	CTG	0	0	73.7
CU329671.1 	2	285676 	285749 	Ala	AGC	0	0	57.1
CU329671.1 	3	326235 	326305 	Gly	TCC	0	0	60.5
CU329671.1 	4	355920 	355991 	Gln	TTG	0	0	73.7
CU329671.1 	5	464238 	464309 	His	GTG	0	0	66.1
CU329671.1 	6	570156 	570226 	Gly	GCC	0	0	71.4
CU329671.1 	7	658451 	658531 	Met	CAT	658489	658495	57.2
CU329671.1 	8	717076 	717148 	Trp	CCA	0	0	69.1
CU329671.1 	9	820491 	820562 	Glu	CTC	0	0	68.9
CU329671.1 	10	960729 	960800 	His	GTG	0	0	66.1
CU329671.1 	11	1503953	1504024	Thr	TGT	0	0	74.7
CU329671.1 	12	1598511	1598594	Tyr	GTA	1598549	1598558	62.3
CU329671.1 	13	1599706	1599788	Lys	CTT	1599745	1599752	74.7
CU329671.1 	14	1600086	1600159	Ile	AAT	0	0	65.0
CU329671.1 	15	1602188	1602260	Arg	ACG	0	0	71.4
CU329671.1 	16	1618293	1618366	Ile	AAT	0	0	65.0
CU329671.1 	17	1629159	1629241	Val	AAC	1629197	1629205	58.5
CU329671.1 	18	1629902	1629975	Ala	AGC	0	0	57.1
CU329671.1 	19	1643849	1643932	Tyr	GTA	1643887	1643896	62.3
CU329671.1 	20	1645044	1645126	Lys	CTT	1645083	1645090	74.7
CU329671.1 	21	1645424	1645497	Ile	AAT	0	0	65.0
CU329671.1 	22	1774860	1774932	Trp	CCA	0	0	69.1
CU329671.1 	23	1877221	1877292	Pro	AGG	0	0	61.8
CU329671.1 	24	2032160	2032233	Asn	GTT	0	0	81.5
CU329671.1 	25	2069487	2069557	Gly	CCC	0	0	61.2
CU329671.1 	26	2319292	2319363	Pro	AGG	0	0	61.8
CU329671.1 	27	2939715	2939786	Pro	AGG	0	0	61.8
CU329671.1 	28	3350594	3350688	Ser	GCT	3350633	3350643	70.1
CU329671.1 	29	3814134	3814216	Lys	CTT	3814173	3814180	74.7
CU329671.1 	30	3814558	3814641	Tyr	GTA	3814596	3814605	63.9
CU329671.1 	31	3914043	3914121	Leu	AAG	0	0	53.1
CU329671.1 	32	3939227	3939297	Asp	GTC	0	0	61.0
CU329671.1 	33	4031743	4031816	Asn	GTT	0	0	81.5
CU329671.1 	34	4107639	4107710	Glu	CTC	0	0	68.9
CU329671.1 	35	4210126	4210053	Asn	GTT	0	0	78.5
CU329671.1 	36	3360590	3360519	Pro	TGG	0	0	68.2
CU329671.1 	37	3209217	3209139	Leu	AAG	0	0	51.5
CU329671.1 	38	2790446	2790375	Thr	AGT	0	0	79.6
CU329671.1 	39	2768335	2768257	Leu	AAG	0	0	53.1
CU329671.1 	40	2576448	2576376	Phe	GAA	0	0	70.3
CU329671.1 	41	2434374	2434303	iMet	CAT	0	0	54.9
CU329671.1 	42	1825858	1825787	Pro	AGG	0	0	61.8
CU329671.1 	43	1647355	1647283	Arg	ACG	0	0	71.4
CU329671.1 	44	1646900	1646829	Glu	TTC	0	0	58.7
CU329671.1 	45	1646387	1646305	Val	AAC	1646349	1646341	58.5
CU329671.1 	46	1645644	1645571	Ala	AGC	0	0	57.1
CU329671.1 	47	1644745	1644675	Gly	GCC	0	0	71.4
CU329671.1 	48	1644183	1644083	Leu	CAA	1644145	1644127	56.5
CU329671.1 	49	1630122	1630049	Ile	AAT	0	0	65.0
CU329671.1 	50	1619256	1619174	Val	AAC	1619218	1619210	58.5
CU329671.1 	51	1618513	1618440	Ala	AGC	0	0	57.1
CU329671.1 	52	1602417	1602347	Asp	GTC	0	0	61.0
CU329671.1 	53	1601562	1601491	Glu	TTC	0	0	58.7
CU329671.1 	54	1601049	1600967	Val	AAC	1601011	1601003	58.5
CU329671.1 	55	1600306	1600233	Ala	AGC	0	0	57.1
CU329671.1 	56	1599407	1599337	Gly	GCC	0	0	71.4
CU329671.1 	57	1598845	1598745	Leu	CAA	1598807	1598789	56.5
CU329671.1 	58	1598155	1598075	Met	CAT	1598117	1598111	57.2
CU329671.1 	59	1598069	1597996	Asn	GTT	0	0	81.5
CU329671.1 	60	1402541	1402444	Leu	TAA	1402503	1402488	47.5
CU329671.1 	61	1160994	1160893	Arg	CCT	1160958	1160929	56.5
CU329671.1 	62	744835 	744754 	Ser	AGA	0	0	79.7
CU329671.1 	63	602699 	602625 	Lys	TTT	0	0	73.6
CU329671.1 	64	326724 	326652 	Arg	TCT	0	0	70.9
CU329671.1 	65	285459 	285389 	Gly	TCC	0	0	64.4
CU329671.1 	66	258919 	258848 	Gln	CTG	0	0	73.7
CU329671.1 	67	257979 	257908 	Gln	TTG	0	0	73.7
CU329671.1 	68	181064 	180994 	Gly	GCC	0	0	71.4
CU329672.1 	1	71400  	71471  	His	GTG	0	0	66.1
CU329672.1 	2	140967 	141038 	Glu	CTC	0	0	68.9
CU329672.1 	3	578847 	578919 	Arg	TCT	0	0	74.2
CU329672.1 	4	817425 	817498 	Ile	AAT	0	0	61.7
CU329672.1 	5	847701 	847782 	Ser	AGA	0	0	79.7
CU329672.1 	6	925852 	925924 	Arg	ACG	0	0	71.4
CU329672.1 	7	947262 	947335 	Asn	GTT	0	0	81.5
CU329672.1 	8	1066628	1066709	Ser	AGA	0	0	79.7
CU329672.1 	9	1068029	1068099	Asp	GTC	0	0	61.0
CU329672.1 	10	1069166	1069244	Leu	AAG	0	0	53.1
CU329672.1 	11	1071093	1071175	Lys	CTT	1071132	1071139	74.7
CU329672.1 	12	1092437	1092507	Asp	GTC	0	0	61.0
CU329672.1 	13	1092934	1093016	Val	AAC	1092972	1092980	58.5
CU329672.1 	14	1102809	1102909	Leu	CAA	1102847	1102865	56.5
CU329672.1 	15	1105840	1105911	Thr	AGT	0	0	79.6
CU329672.1 	16	1106327	1106399	Arg	ACG	0	0	71.4
CU329672.1 	17	1253193	1253287	Ser	GCT	1253232	1253242	70.1
CU329672.1 	18	1475034	1475116	Lys	CTT	1475073	1475080	74.7
CU329672.1 	19	1689713	1689809	Ser	TGA	1689750	1689764	76.5
CU329672.1 	20	1689817	1689888	iMet	CAT	0	0	54.9
CU329672.1 	21	1701899	1701972	Asn	GTT	0	0	81.5
CU329672.1 	22	1788949	1789020	Pro	AGG	0	0	61.8
CU329672.1 	23	1844639	1844710	His	GTG	0	0	66.1
CU329672.1 	24	1863131	1863202	Gln	TTG	0	0	70.4
CU329672.1 	25	2037352	2037422	Gly	TCC	0	0	63.4
CU329672.1 	26	2072080	2072174	Ser	GCT	2072119	2072129	70.1
CU329672.1 	27	2139478	2139408	Asp	GTC	0	0	61.0
CU329672.1 	28	2075062	2074991	Gln	TTG	0	0	70.4
CU329672.1 	29	1776073	1775992	Ser	AGA	0	0	79.7
CU329672.1 	30	1361161	1361090	Thr	TGT	0	0	75.7
CU329672.1 	31	1206819	1206747	Val	TAC	0	0	72.1
CU329672.1 	32	1142264	1142192	Phe	GAA	0	0	69.0
CU329672.1 	33	1139618	1139536	Lys	CTT	1139579	1139572	74.7
CU329672.1 	34	1106557	1106487	Asp	GTC	0	0	61.0
CU329672.1 	35	1106060	1105978	Val	AAC	1106022	1106014	58.5
CU329672.1 	36	1097570	1097499	Glu	CTC	0	0	68.9
CU329672.1 	37	1096185	1096085	Leu	CAA	1096147	1096129	56.5
CU329672.1 	38	1093154	1093083	Thr	AGT	0	0	79.6
CU329672.1 	39	1092667	1092595	Arg	ACG	0	0	71.4
CU329672.1 	40	1068254	1068182	Arg	ACG	0	0	71.4
CU329672.1 	41	1067164	1067092	Arg	TCG	0	0	63.3
CU329672.1 	42	1065860	1065778	Val	AAC	1065822	1065814	58.5
CU329672.1 	43	1065117	1065044	Ala	AGC	0	0	57.1
CU329672.1 	44	820637 	820567 	Gly	GCC	0	0	71.4
CU329672.1 	45	473280 	473199 	Ser	AGA	0	0	79.7
CU329672.1 	46	331300 	331228 	Phe	GAA	0	0	69.0
CU329672.1 	47	113786 	113716 	Gly	GCC	0	0	71.4
X54421.1   	1	2857   	2929   	Lys	TTT	0	0	55.4
X54421.1   	2	2968   	3050   	Ser	GCT	0	0	32.9	pseudo
X54421.1   	3	3060   	3130   	Asn	GTT	0	0	60.8
X54421.1   	4	4591   	4665   	Met	CAT	0	0	39.6
X54421.1   	5	9818   	9888   	Arg	TCT	0	0	59.7
X54421.1   	6	9920   	9992   	Thr	TGT	0	0	60.8
X54421.1   	7	14159  	14230  	Phe	GAA	0	0	54.6
X54421.1   	8	14314  	14385  	Gly	TCC	0	0	37.9	pseudo
X54421.1   	9	14394  	14476  	Leu	TAA	0	0	40.9
X54421.1   	10	14492  	14563  	Trp	CCA	0	0	43.2	pseudo
X54421.1   	11	14596  	14669  	Leu	TAG	0	0	48.7
X54421.1   	12	15551  	15622  	His	GTG	0	0	48.5
X54421.1   	13	16662  	16734  	Ile	GAT	0	0	46.9	pseudo
X54421.1   	14	17166  	17238  	Val	TAC	0	0	55.6
X54421.1   	15	17460  	17532  	Arg	TCG	0	0	51.7
X54421.1   	16	17542  	17613  	Met	CAT	0	0	39.5
X54421.1   	17	17635  	17716  	Ser	TGA	0	0	48.2
X54421.1   	18	18057  	18129  	Ala	TGC	0	0	45.3	pseudo
X54421.1   	19	18404  	18475  	Glu	TTC	0	0	44.8
FungiWork.ipynb
GCA_000002945.2.zip
GCA_000002945.2_ASM294v2_genomic.fna_trna.fasta
GCA_000002945.2_dir/
LICENSE
README.md
delete_me.csv
eukaryotes_ncbi_temperatures.csv
fungi-work-vs.ipynb
fungi-work-vs.qmd
temperature_data.tsv


==========


FungiWork.ipynb
GCA_000002945.2_ASM294v2_genomic.fna_trna.fasta
LICENSE
README.md
delete_me.csv
eukaryotes_ncbi_temperatures.csv
fungi-work-vs.ipynb
fungi-work-vs.qmd
temperature_data.tsv